version: '3'
services:
  top.api:
    image: top-api:latest
    container_name: top-api
    restart: always
    ports: 
      - 4000:4000
    volumes:
      - ./.env:/opt/app/.env
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27019:27019