version: '3'
services:
  s-prof-e-commerce-shop:
    image: s-prof-e-commerce-shop:latest
    container_name: s-prof-e-commerce-shop
    restart: always
    ports: 
      - 4000:4000
    volumes:
      - ./.env:/app/.env
    environment:
      - DATABASE=${DATABASE?:}
  
  mongo:
    image: mongo
    container_name: mongo-s-prof-e-commerce-shop
    restart: always
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017