openapi: 3.0.1
info:
  title: S-Prof
  description: Интернет магазин промышленного кухонного оборудования
  contact:
    email: vladislav.pestsov@gmail.com
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/v1

paths:
  /user/signup:
    post:
      summary: Регистрация нового пользователя
      tags:
        - authentification
      requestBody:
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/signup_form'
        required: true
      responses:
        201:
          description: Пользователь cоздан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/signup_201'
        
        400: 
          description: Заполнены не все поля
          content:
            aplication/json:
              schema:
                $ref: '#/components/schemas/empty_fields_400'        
                
        409: 
          description: Пользователь с данным Email уже существует
          content:
            aplication/json:
              schema:
                $ref: '#/components/schemas/dublicate_email_409'

components: 
  schemas:
    signup_form:
      $ref: './auth.yml/#components/schemas/signup_form'
    
    signup_201:
      $ref: './auth.yml#/signup_201'
